/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Title = string
export type Disabled = boolean
export type Readonly = boolean
export type Narrow = boolean
export type Label = string
export type Description = string
export type Steps = UISchemaStep[]
/**
 * whether or not the labels should be interpreted as locale keys
 */
export type Translate = boolean
/**
 * list of property names to determine form field order
 */
export type Order = string[]
export type Title1 = string
export type Description1 =
  | string
  | {
      [k: string]: string
    }
export type Help =
  | string
  | UIFormattedString
  | {
      [k: string]: string
    }
export type Key = string
export type Widget = string
export type Field = string
export type Data1 = string
export type Placeholder = string
export type Autofocus = boolean
export type Minimumrows = number
export type Text = string
export type Classes = string
export type Disabled1 = boolean | string
export type Readonly1 = boolean
export type Icon = string
export type Step = number
export type Type = string[] | string
export type Conditions = UICondition[]

/**
 * Exported JSON+UI schema dictionary. JSONSchema is in `data` and ui is in `ui`
 */
export interface FormSchema {
  data: Data
  ui: UISchema
  [k: string]: any
}
export interface Data {
  [k: string]: any
}
/**
 * UISchema object that is associated with a JSONSchema. Contains form
 * configuration information, and a dictionary of properties.
 */
export interface UISchema {
  config?: UISchemaConfig
  properties?: Properties
  [k: string]: any
}
export interface UISchemaConfig {
  title?: Title
  disabled?: Disabled
  readonly?: Readonly
  narrow?: Narrow
  steps?: Steps
  translate?: Translate
  order?: Order
  [k: string]: any
}
export interface UISchemaStep {
  label: Label
  description?: Description
  [k: string]: any
}
export interface Properties {
  [k: string]: UIProp
}
/**
 * Define UI attributes for the current FormProp
 */
export interface UIProp {
  title?: Title1
  description?: Description1
  help?: Help
  widget?: Widget
  field?: Field
  data?: Data1
  placeholder?: Placeholder
  autoFocus?: Autofocus
  minimumRows?: Minimumrows
  text?: Text
  classes?: Classes
  disabled?: Disabled1
  readonly?: Readonly1
  icon?: Icon
  step?: Step
  messages?: Messages
  conditions?: Conditions
  [k: string]: any
}
/**
 * Useful when you want to specify a translation entry with format arguments
 */
export interface UIFormattedString {
  key: Key
  args: Args
  [k: string]: any
}
export interface Args {
  [k: string]: number | string
}
export interface Messages {
  [k: string]: UIFormattedString | string
}
/**
 * Determine if a field should be shown based some combination of other
 * fields in the Schema.
 */
export interface UICondition {
  type?: Type
  [k: string]: any
}
