version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "live"
update_configs:
  - package_manager: "javascript"
    directory: "/libraries/typescript"
    update_schedule: "live"
